### Get all orders
GET http://localhost:5001/api/v1/orders/all
Content-Type: application/json
API_KEY: admin_key_2024

### Get order by id
GET http://localhost:5001/api/v1/orders/1
Content-Type: application/json
API_KEY: admin_key_2024

### Get order item by id
GET http://localhost:5001/api/v1/orders/1/items
Content-Type: application/json
API_KEY: admin_key_2024

### Create new Order
POST http://localhost:5001/api/v1/orders
Content-Type: application/json
API_KEY: admin_key_2024

{
  // Request body remains the same
}

### Update Order
PUT http://localhost:5001/api/v1/orders/1
Content-Type: application/json
API_KEY: admin_key_2024

{
  // Request body remains the same
}

### Delete order
DELETE http://localhost:5001/api/v1/orders/1
Content-Type: application/json
API_KEY: admin_key_2024