### Get all shipments
GET http://localhost:5001/api/v1/shipments/all
Content-Type: application/json
API_KEY: admin_key_2024

### Get shipment by id
GET http://localhost:5001/api/v1/shipments/10102
Content-Type: application/json
API_KEY: admin_key_2024

### Get shipment items by id
GET http://localhost:5001/api/v1/shipments/1/items
Content-Type: application/json
API_KEY: admin_key_2024

### Get shipments by order id
GET http://localhost:5001/api/v1/shipments/1/orders
Content-Type: application/json
API_KEY: admin_key_2024

### Create shipment
POST http://localhost:5001/api/v1/shipments
Content-Type: application/json
API_KEY: admin_key_2024

{
  // Request body remains the same
}

### Update shipment
PUT http://localhost:5001/api/v1/shipments/5
Content-Type: application/json
API_KEY: admin_key_2024

{
  // Request body remains the same
}

### Delete shipment
DELETE http://localhost:5001/api/v1/shipments/5
Content-Type: application/json
API_KEY: admin_key_2024