name: CI Build

on:
  push:
    branches: [ "CI/CD_c#" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./CSharpAPI

      - name: Build solution
        run: dotnet build ./ --no-restore --configuration Release

      - name: List csharpapi dir
        run: ls ./csharpapi

