name: CI Workflow

on:
  push:
    branches: [ "CI/CD_C#2.0" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./CSharpAPI/CSharpAPI.csproj

      - name: Build solution
        run: dotnet build ./CSharpAPI/CSharpAPI.csproj --no-restore --configuration Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./CSharpAPI/bin/Release

  test:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies for tests
        run: dotnet restore ./Test/Test.csproj

      - name: Run tests
        run: dotnet test ./Integration_Testing/Integration_Testing.csproj --configuration Release --logger "trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/test-results.trx
