name: CI Build

on:
  push:
    branches: [ "CI/CD_c#" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./CSharpAPI/CSharpAPI.csproj

      - name: Build solution
        run: dotnet build ./CSharpAPI/CSharpAPI.csproj --no-restore --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Testing/Testing.csproj

      - name: Run tests
        run: |
          mkdir -p TestResults
          dotnet test ./Testing/Testing.csproj --configuration Release --logger "trx;LogFileName=TestResults/test-results.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=coverage/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: '**/coverage.cobertura.xml'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/test-results.trx

      - name: Generate test summary
        uses: dorny/test-reporter@v1
        with:
          name: .NET Test Results
          path: TestResults/test-results.trx
          reporter: dotnet-trx
