name: CI Workflow

on:
  push:
    branches: [ "CI/CD_C#2.0" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./CSharpAPI/CSharpAPI.csproj

      - name: Build solution
        run: dotnet build ./CSharpAPI/CSharpAPI.csproj --no-restore --configuration Release
