name: CI/CD Workflow
on:
  push:
    branches: ["Testingbranch"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Run Tests with Pytest
        run: |
          pytest --cov --cov-report term --cov-report xml:coverage.xml

      - name: Generate Coverage Report
        run: |
          coverage report --fail-under=100 >> $GITHUB_STEP_SUMMARY
          
      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
