name: CI Workflow

on:
  push:
    branches: [ "CICDTestingBranch" ]
##gasdasdfagsd
jobs:
  # Job 1: Build
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 httpx requests  # Install requests and other dependencies here
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  # Job 2: Test
  test:
    needs: build  # This job will only run after the 'build' job has completed
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov httpx requests coverage 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


      # Start the API server in the background and log output
      - name: Start API server
        run: |
          python3 PythonAPI/api/main.py &

      - name: Run code coverage
        run: |
          coverage run -m pytest
          coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
          coverage report --fail-under=80  # Fail the build if coverage is below 80%

      - name: Store coverage report
        uses: actions/upload-artifact@v4
        with:
          path: coverage.xml  
        if: ${{ failure() }}  

  # Job 3: Deployment to Production
  deployment:
    needs: test  # This job will run after the 'test' job has completed
    runs-on: self-hosted
    environment: production  # This is where the deployment happens
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest httpx
      - name: Deploy to Production
        run: |
          echo "Deploying application to production environment..."
          # Add your deployment-specific steps here
          # Example: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} 'bash /path/to/deploy.sh'
